### ISSUE TITLE
[FEATURE] View older conversations

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx-webtexting#37]
When a Web Texting instance has many existing conversations, it is hard to view older conversations unless you know the phone number your looking to view and you send them a new message.

Goals:

- [x] Enable users to scroll further down the list of conversations (say, lazy load conversation threads into the conversations list)
- [x] Move the start conversation button up in the Conversations list so its always visible
- [x] Let users search existing conversations by phone number or contact name (low priority)
- [ ] #67

**Comment by dunkeltron** [comment]
Yeah dev oversight on this one.
First, I've already moved the start conversation out of the threadpreview container to make it accessible since it's the current workaround.
Second, I've removed a 25 result limit on the query we use to build the threadpreview components. (this does mean users with a ton of conversations will have a massive page load time but that's why I'm working on the "search for conversation" view)
After we've got the new search view finished I want to implement a backfill conversations functionality similar to how we backfill messages in the thread view

**Comment by dunkeltron** [comment]
I've got the search database and initial limit implemented. Still working on the lazy loading aspect.
For the message search do you want to have search all threads _and_ search specific threads (one would be in the ThreadSearch component the other would be in the conversation component )

**Comment by dunkeltron** [comment]
converted 4th task to separate issue #67 because it is not related to viewing older conversations at the moment.

**Comment by uncheckederror** [comment]
Closing this as completed now that most of the work is live and the remaining work has been bumped out into a separate issue.
